name: Hello CI
run-name: Hello ${{ github.actor }}, this action was triggered by ${{ github.event_name }}
on: [push, pull_request]
jobs:
  hello_job:
    name: Hello CI job
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, I'm runnung on ${{ runner.os }}"
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: list files
        run: |
          ls ${{ github.workspace}}
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          #pip install -r requirements.txt
      - run: echo "Hello CI" > hello.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello
          path: hello.txt
          retention-days: 1
          if-no-files-found: error
